slam_toolbox:
  ros__parameters:

    # Frames principais
    odom_frame: odom
    map_frame: map
    base_frame: robot_center
    scan_topic: /scan

    # Modo de operação
    mode: mapping

    # Parâmetros de Tempo e Transformação
    # Aumentar esses valores ajuda se o mapa não estiver sendo gerado por delay
    transform_publish_period: 0.05
    transform_timeout: 1.0
    tf_buffer_duration: 30.0
    lookup_transform_timeout: 0.5
    
    # Simulação
    use_sim_time: true

    # Parâmetros do Mapa
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 20.0
    minimum_time_interval: 0.1
    stack_size_to_use: 40000000

    # Parâmetros de Scan Matching
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    
    # Loop Closure (Fechamento de ciclo)
    # Ativado para corrigir o mapa quando o robô volta a um lugar conhecido
    do_loop_closing: true
    loop_search_distance: 8.0
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # Parâmetros de Scan Matcher Fine
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 1.5
