pc_to_ls:
  ros__parameters:
    target_frame: livox_frame

    transform_tolerance: 0.5

    min_height: -10.0
    max_height: 10.0

    angle_min: -3.1415
    angle_max: 3.1415
    angle_increment: 0.0174

    scan_time: 0.1

    range_min: 0.3
    range_max: 50.0

    reliability: best_effort
    use_sim_time: true