remap:
  ros__parameters:
    use_sim_time: true

    in_odom: /dog_odom
    in_scan: /scan

    out_odom: /dog_odom_slam
    out_scan: /scan_slam

    odom_frame: odom_slam
    base_frame: base_link_slam
    lidar_frame: lidar_link_slam

    normalize_quaternion: true