remap:
  ros__parameters:
    use_sim_time: true
    in_odom: /dog_odom
    in_scan: /scan
    out_odom: /dog_odom_fixed
    out_scan: /scan_fixed
    odom_frame: odom
    base_frame: base_link
    lidar_frame: lidar_link
    normalize_quaternion: true
